### ISSUE TITLE
What is the difference between Query Tokens and [SLS] tokens

### ISSUE THREAD

**Issue by xushilin1** [MendelXu/SAN#1]
or are they the same thing?

**Comment by MendelXu** [comment]
Our implementation distinguishes between Query Tokens, which group pixels and generate class-agnostic mask proposals, and [SLS] tokens, which are specifically designed to retrieve category-relevant information from CLIP. Although I did not attempt to use the same tokens for both purposes, it is possible that doing so with careful tuning may still yield positive results.
