### ISSUE TITLE
关于一些论文细节

### ISSUE THREAD

**Issue by lebron-2016** [MendelXu/SAN#15]
尊敬的作者您好：

&nbsp;非常感谢您对开放词汇图像分割做出的巨大贡献。
&nbsp;我拜读了您的论文，在这里想请教您两个问题。
&nbsp;&nbsp;1. 请问您对于query tokens和[SLS] tokens的个数设置是相同的吗？
&nbsp;&nbsp;2. 
![image](https://github.com/MendelXu/SAN/assets/80045218/3e5ff01f-79b1-4a2c-a083-d47682f976d8)
&nbsp;&nbsp;请问这里的类别名称指的是当前数据集的所有类别名称吗？（并用C表示其个数）

&nbsp;期待您的回复！感谢！

**Comment by MendelXu** [comment]
1. 是的。
2. 是的。

**Comment by lebron-2016** [comment]
> 1. 是的。
> 2. 是的。

谢谢您的解答！

针对第二个问题我还有一点困惑，我对于开放词汇的理解是基于一个广泛的开放词汇表，如果使用数据集类别词汇表是不是更类似于zero-shot的设定，这里应该如何理解呢？

期待您的回复！感谢！

**Comment by MendelXu** [comment]
你说的是对的，按道理应该是一个任意的广泛的词汇表，只是这里会涉及到怎么评测的问题，使用数据集类别只是因为好做评测。
