### ISSUE TITLE
how to get pcontext-full dataset

### ISSUE THREAD

**Issue by sunwhw** [MendelXu/SAN#16]
Thanks for you great work! I met a problem when i prepare the dataset
![image](https://github.com/MendelXu/SAN/assets/48038000/3956ab67-a3a8-4aee-b79a-cd1c5cd8948c)
What value should I set for anno dir?
i guess the anno dir should be set "dataset/pcontext-full/VOCdevkit/VOC2010/Annotations" but "xml" is not compatible with 'mat' which assigned in code? 
what should i do?
![image](https://github.com/MendelXu/SAN/assets/48038000/bb7b4a25-62d6-4616-b4e7-ae14623c9b50)

**Comment by MendelXu** [comment]
You can download it from here. http://www.eecs.berkeley.edu/Research/Projects/CS/vision/grouping/semantic_contours/benchmark.tgz

**Comment by sunwhw** [comment]
oh!  Thanks
