### ISSUE TITLE
 SAN ensemble

### ISSUE THREAD

**Issue by sunwhw** [MendelXu/SAN#17]
Thanks for your great work! Is there any code implementation about "SAN ensemble"(mentioned in Table 2 of the paper) ?

**Comment by MendelXu** [comment]
Sorry that I have not prepared a clean code to do that. But you may look at https://gist.github.com/MendelXu/105c7b91ba4b59b75acd488f6304b50f for a reference.
Note that the input is path of a file which contains the command args of different models, like:
```
--config-file a.yaml MODEL.WEIGHTS ./output/a/model
--config-file b.yaml MODEL.WEIGHTS ./output/b/model
```

**Comment by sunwhw** [comment]
Oh, Thanks!
