### ISSUE TITLE
There is also a question about "emsemble"

### ISSUE THREAD

**Issue by sunwhw** [MendelXu/SAN#18]
There is also a question about the emsemble, what should the weight be set to emsemble the origin san model and the model fine-tuned on coco stuff? or could you tell me the range the weights should be set? 
```python
w = float(os.environ["EWEIGHT"])
sem_seg = torch.pow(sem_segs[0][:min_cls],w)*torch.pow(sem_segs[1][:min_cls],1-w)
```

**Comment by sunwhw** [comment]
and when you fine-tune on the coco stuff, do your model is totally samed as the SAN?

**Comment by sunwhw** [comment]
and when you fine-tune on the coco stuff, is your model totally samed as the SAN?

**Comment by MendelXu** [comment]
1) In most situation, the weight is set to 0.5. 
2) Yes, the model is exactly the same network as SAN.
