### ISSUE TITLE
Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

### ISSUE THREAD

**Issue by luluxiu17122** [MendelXu/SAN#22]

**Comment by APeiZou** [comment]
@luluxiu17122 我也出现了相同的问题，请问您是怎么解决的呢

**Comment by ChunmengLiu1** [comment]
> @luluxiu17122 我也出现了相同的问题，请问您是怎么解决的呢
我也出现了相同的问题，请问您是怎么解决的呢

**Comment by ChunmengLiu1** [comment]
> @luluxiu17122 我也出现了相同的问题，请问您是怎么解决的呢

你好，我解决了这个问题。这是由于我没有使用prepare_coco_stuff.py处理coco-stuff数据集，可以参考https://github.com/KU-CVLAB/CAT-Seg/blob/main/datasets/README.md这个准备数据集。
