### ISSUE TITLE
pointsample

### ISSUE THREAD

**Issue by sunwhw** [MendelXu/SAN#24]
When compare the predition_mask with gt_mask, i find you used the pointsample() to align their size, do you think it harms the learning performance? Have you ever tried other methods or the pointsample() is always used for detr's-like model?

**Comment by MendelXu** [comment]
Sorry, we didn't ablate its neceesarity. However, you can refer to the original mask2former paper, it seems the pointsample would not downgrade the performance.

**Comment by sunwhw** [comment]
oh! Well! Thanks!
