### ISSUE TITLE
Visualize

### ISSUE THREAD

**Issue by zzy0428** [MendelXu/SAN#26]
How to visualize your quantitative results. Do you have any scripts for generating the semantic segmentation results. I'm not quite into the detectron2 framework.
Thank you!

**Comment by zzy0428** [comment]
Is there any way to visualize the generated masks?

**Comment by zzy0428** [comment]
I already figured it out the way of generating semantic segmentation results. But could you point out the masks  image generation according to your proposals ?

**Comment by MendelXu** [comment]
Did you mean generating mask proposals? The mask proposals are not saved by default. You have to add breakpoint manually and then you are able to save the mask proposals.

**Comment by hly1999** [comment]
> I already figured it out the way of generating semantic segmentation results. But could you point out the masks image generation according to your proposals ?

May I ask how to generate semantic segmentation results? Thanks
