### ISSUE TITLE
Model structure

### ISSUE THREAD

**Issue by chaoyupeng** [MendelXu/SAN#27]
Hi Mengde,
I'm trying to replicate the model demo, in the paper, the demo on hugging face is able to accepts text based prompt query on the image, we just want to know which part of the code correspond to this functionality, I went through the code and was unable to locate the this part, can you give me some general guide lines?
Cheers,
Yupeng

**Comment by MendelXu** [comment]
Sorry for late reply. It is here https://github.com/MendelXu/SAN/blob/37171766dfa992276d28bac7c4b6c7e20d91ae7e/predict.py#L128
