### ISSUE TITLE
Why using a masked self-attention layer when calculating the X[SLS]

### ISSUE THREAD

**Issue by Harry-zzh** [MendelXu/SAN#3]
Thank you for your excellent work. In the figure 3 of the paper, the black squares means query is not updated by key. Could you kindly explain why these queries are intentionally not updated by key? Why not set them to be updated normally by key? I am curious if this has any potential impact on the results.

**Comment by MendelXu** [comment]
Sorry for late reply. We didn't update the image tokens query with the [sls] token for two reason: 1) If the image tokens are updated with the [SLS] token, the image features will be different from those in the original CLIP, which may affect the recognition performance; 2) As denoted in the paper, updating image tokens without [sls] tokens is more friendly to GPU resource as it could be rewritten into cross-attention format, making it possible to increase the [sls] tokens linearly.  However, I didn't test the normally updated one. I think it may need careful tuning as the initial mask prediction may be terrible.
