### ISSUE TITLE
关于使用Prompt提升分割效果

### ISSUE THREAD

**Issue by H1NATA111** [MendelXu/SAN#31]
感谢您出色的工作！！
注意到您论文附录中涉及使用Prompt提升分割效果，请问具体实施中，是训练、测试都使用加入Prompt的类别标签，还是使用单个词汇的标签训练再在测试时加入Prompt呢？
如您能解惑，不胜感激！！

**Comment by MendelXu** [comment]
训练测试的时候都用，可以参考现在的训练脚本
