### ISSUE TITLE
Detail about 'background' class

### ISSUE THREAD

**Issue by develop-productivity** [MendelXu/SAN#36]
Hi, thanks for your great work.

I have a question about the classifier in this paper 3.3.1 Pixel-wise Side Adapter Network:
> where M denotes the category number of training set.

I want to know whether the 'background' class contained in the training set? If you used a background class, is it learnable or fixed?

**Comment by MendelXu** [comment]
It is learnable.

**Comment by develop-productivity** [comment]
Oh thanks!
I have one more request. Can you release your training and testing logs? This will help me reproduce your results. 
Thank you so much.

**Comment by MendelXu** [comment]
It was saved here https://github.com/MendelXu/SAN/blob/main/resources/san_vit_b_16.log

See https://github.com/MendelXu/SAN#pretrained-weights for all logs.

**Comment by develop-productivity** [comment]
Oh, It turns out it’s in the readme, forgive me for being careless.😝
