### ISSUE TITLE
训练自己的数据集

### ISSUE THREAD

**Issue by HarryMark927** [MendelXu/SAN#39]
作者你好！抱歉打扰
想请教一下如果我想在自己的数据集上进行训练和测试，我需要在哪几个文件上进行修改呢？

**Comment by MendelXu** [comment]
1. Add a script to define your dataset in `san/data/datasets`. You can refer to https://github.com/MendelXu/SAN/blob/main/san/data/datasets/register_voc.py. Remember to import it in `san/data/datasets/__init__.py`.
2. Train the model with `python train_net.py --eval-only --config-file <CONFIG_FILE> --num-gpus <NUM_GPU> OUTPUT_DIR <OUTPUT_PATH> MODEL.WEIGHTS <TRAINED_MODEL_PATH> MODEL.SAN.NUM_CLASSES [NUM_OF_CLASS]`.

**Hint** To make the training process work properly, please check the batch data before training for a long time (You can add a breakpoint [Here](https://github.com/MendelXu/SAN/blob/81a9a2bd79d433292d46cfa0597caea5005e0116/san/model/san.py#L149) .

**Comment by HarryMark927** [comment]
sorry to bother you again.
could you tell me what should I input  the tow parameters about  OUTPUT_DIR <OUTPUT_PATH> and MODEL.WEIGHTS <TRAINED_MODEL_PATH> or please show me an example about the training command.
my propose is to train a new dataset in your model and test it, and I have already prepared the dataset as you said like voc.
Thank you so much!
