### ISSUE TITLE
Performance difference between the provided log and my re-implementation.

### ISSUE THREAD

**Issue by dzh19990407** [MendelXu/SAN#4]
Thanks for your appealing work!
After preparing the required datasets, I download the pretrained weights of "SAN-ViT-B/16" model and evaluate it using the provided script on all datasets. However, there are small differences between the provided log file and mine.

I provided my evaluation [log.txt](https://github.com/MendelXu/SAN/files/11150078/log.txt).

What might be the reason for this difference?

**Comment by dzh19990407** [comment]
I retrain the 'SAN-ViT-B/16' using the default config `san_clip_vit_res4_coco.yaml`. The evaluation results during the training phase and testing phase are the same. It seems that the above performance difference is not caused by the error of training or testing code. 
Are there any other reasons for the performance gap?

**Comment by MendelXu** [comment]
The gap seems small. I am not sure why it happens. Is it possible due to different running environment? The provided models are trained on 8 A100@40GB with the provided docker.

**Comment by dzh19990407** [comment]
Thanks for your reply, I will check the environment.

**Comment by tro0o** [comment]
@dzh19990407 I note that the miou of pcontext_full_sem_seg_val in san_vit_b_16.log is 16.7053，but in your paper the miou of PC-459 is 12.6。Aren't these two metrics evaluating the same dataset?

**Comment by dzh19990407** [comment]
@tro0o I'm not the author of the paper. And I have the same doubts about the performance.

**Comment by MendelXu** [comment]
> @dzh19990407 I note that the miou of pcontext_full_sem_seg_val in san_vit_b_16.log is 16.7053，but in your paper the miou of PC-459 is 12.6。Aren't these two metrics evaluating the same dataset?

It is evaluated on the same dataset. However, the code is not the same as the one used in the paper.
The main differences are:
- I rewrite the whole project to make it simpler and more readable. 1) Some dirty parts (like manually clipping the value of some layers) in the old code are removed. 2) some code modified based on original clip ( openai version) are removed and instead the package `open_clip` is used.
- The running enviroment is different. In the paper, we use pytorch 1.9.0 for experiments. However, I think it is somewhat out of date now, so I switch to torch 1.13.0 in this project.
