### ISSUE TITLE
CLIP image encoder

### ISSUE THREAD

**Issue by scm-later** [MendelXu/SAN#40]
I have two questions.
(1)At present,I have a ViT-B/32 weight that I trained by myself,but SAN's pre-training weight is ViT-B/16
How can I use my pre-training weight ViT-B/32 for SAN ?   AS we all konw, official clip is trained of ViT-B/32   ViT-B/16 and ResNet
(2)why doesn't the CLIP image encoder use ResNet
Thanks!!

**Comment by MendelXu** [comment]
1) You may have to edit the config to set the clip model name and re-train your own model.
2) It is eaiser to evaluate the scaling law of vit based model as more vit based models with different size are provided.

**Comment by SCM556** [comment]
Thank you for your reply
