### ISSUE TITLE
About Visualization of Results

### ISSUE THREAD

**Issue by hly1999** [MendelXu/SAN#41]
I would like to ask where the visualization part of the results in the code is located.Thanks

**Comment by MendelXu** [comment]
You can find it [here ](https://github.com/MendelXu/SAN/blob/81a9a2bd79d433292d46cfa0597caea5005e0116/predict.py#L148)

**Comment by hly1999** [comment]
Sorry，I want to know how to see the segmented image，it doesn't seem to be in the output folder.

**Comment by MendelXu** [comment]
Could you provide the command you used?

**Comment by hly1999** [comment]
python train_net.py --config-file configs/san_clip_vit_res4_coco.yaml --num-gpus 4  OUTPUT_DIR ./output2/trained_vit_b16
I cannot find the segmented JPG image in the output folder.

**Comment by MendelXu** [comment]
It will not produce the segmented image directly. The results are stored in `./output2/trained_vit_b16/inference/*.json`. If you want to visualize it with https://gist.github.com/MendelXu/052d65bd51c48887274fd985eb0f3ad1. Before using it, change line 11 to `from san import *`

**Comment by hly1999** [comment]
OK，thank you for your response.

**Comment by hly1999** [comment]
https://github.com/MendelXu/SAN/issues/41#issuecomment-1923913513,in this link,
![image](https://github.com/MendelXu/SAN/assets/63353950/ef08a77e-0fb1-46c5-b64d-3c42a79e32f4)
What are these parameters filled in separately？

**Comment by hly1999** [comment]
我在运行上面的可视化文件时遇到了这个问题
![image](https://github.com/MendelXu/SAN/assets/63353950/c74a5739-8fda-4f3d-8139-6f31c8a95553)
AttributeError: Attribute 'stuff_dataset_id_to_contiguous_id' does not exist in the metadata of dataset 'pcontext_full_sem_seg_val'. Available keys are dict_keys(['name', 'stuff_classes', 'image_root', 'sem_seg_root', 'evaluator_type', 'ignore_label']).
请问这个是什么原因

**Comment by MendelXu** [comment]
refer to https://github.com/MendelXu/SAN/commit/3998b05867bb9879398727bf8478700ce3c005fb
