### ISSUE TITLE
about the pretrained weights

### ISSUE THREAD

**Issue by ChunmengLiu1** [MendelXu/SAN#45]
Hi! Thank you for your excellent work!

Do you use pretrained weights? where should I set in the code? Thank you!

**Comment by MendelXu** [comment]
I didn't. But it is easy to specify.  
1.  Set the model name by `cfg.MODEL.SIDE_ADAPTER.VIT_NAME`.
2. Specify the path of the preatrined weights by `cfg.MODEL.SIDE_ADAPTER.PRETRAINED`.

**Comment by ChunmengLiu1** [comment]
Got it! Thank you so much!
