### ISSUE TITLE
How to change the dataset folder position? 

### ISSUE THREAD

**Issue by ChunmengLiu1** [MendelXu/SAN#47]
Sorry for bothering again.
How to change the dataset folder position? 
Thanks!

**Comment by MendelXu** [comment]
Set enviroment variable `DETECTRON2_DATASETS`  before your training. For example, if your dataset is `/some/folder/coco`, set it to `/some/folder`

**Comment by ChunmengLiu1** [comment]
Thanks! The code is well encapsulated!
