### ISSUE TITLE
About training cost.

### ISSUE THREAD

**Issue by OliverHxh** [MendelXu/SAN#5]
Dear authors, thanks for your amazing work. Could you tell me how long the training (CLIP VIT-B/16 and ViT-L/14) takes on  COCO Stuff dataset using 8 NVIDIA V100 GPUs? 
Thanks!

**Comment by MendelXu** [comment]
We have communicated on the WeChat 😃 . It may take about 18 hours to train the ViT-B/16 model on 8 V100 GPUs.

**Comment by 007invictus** [comment]
Hello,I am not sure of the training time gap between the different frozen layer setting.Will the learnable CLIP pos_embbeding increase the time and memory of training because it will introduce more Computational Graph？

**Comment by 007invictus** [comment]
> Hello,I am not sure of the training time gap between the different frozen layer setting.Will the learnable CLIP pos_embbeding increase the time and memory of training because it will introduce more Computational Graph？

I think maybe it will make the gradient flow back to the early CLIP model stage?
