### ISSUE TITLE
关于COCO-Stuff171数据集准备的问题

### ISSUE THREAD

**Issue by ashun989** [MendelXu/SAN#50]
这是一个很棒的工作！在此向您汇报一个数据准备的小问题，使得该代码更容易为大家使用：
在 `Data Preparation` 中，您提到使用 [SimSeg](https://github.com/MendelXu/zsseg.baseline) 中的脚本去准备 COCO-Stuff 数据集，也就是提前将不连续的类别标签转化为连续的类别标签；
但是在本项目[注册 COCO-Stuff171 数据集时](https://github.com/MendelXu/SAN/blob/81a9a2bd79d433292d46cfa0597caea5005e0116/san/data/datasets/register_coco_stuff_164k.py#L189)，代码表明您仍然使用原始的不连续标签；
因此在准备COCO-Stuff171时，不需要再生成一个连续的标签放在 `$DETECTRON2_DATASETS/coco/stuffthingmaps_detectron2` 下，直接使用[原始标注](http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/stuffthingmaps_trainval2017.zip) 即可；
实践表明，修正这一处错误后，使用您提供的检查点才能在COCO-Stuff171上获得正确的性能，并在也可以正常训练。

**Comment by GOZIHUATANEJO** [comment]
感谢您的提示，还想请教您在训练的过程中是否遇到过tgt_ids中的数字超出了out_prob的范围的情况,具体位置在Breadcrumbs[SAN](https://github.com/MendelXu/SAN/tree/main)/[san](https://github.com/MendelXu/SAN/tree/main/san)/[model](https://github.com/MendelXu/SAN/tree/main/san/model)
/matcher.py的116行cost_class = -out_prob[:, tgt_ids]，是因为我没有运行https://github.com/MendelXu/zsseg.baseline/blob/master/datasets/prepare_coco_stuff_164k_sem_seg.py的缘故吗

**Comment by GOZIHUATANEJO** [comment]
感谢您的提示，还想请教您在训练的过程中是否遇到过tgt_ids中的数字超出了out_prob的范围的情况,具体位置在Breadcrumbs[SAN](https://github.com/MendelXu/SAN/tree/main)/[san](https://github.com/MendelXu/SAN/tree/main/san)/[model](https://github.com/MendelXu/SAN/tree/main/san/model)
/matcher.py的116行cost_class = -out_prob[:, tgt_ids]，是因为我没有运行下列代码的缘故吗？https://github.com/MendelXu/zsseg.baseline/blob/master/datasets/prepare_coco_stuff_164k_sem_seg.py

**Comment by ashun989** [comment]
反倒是您提醒了我，我因为之前什么时候已经处理得到了一个标签连续的标注目录，再次在上面做处理就出错了。
你的问题应该就是需要用那个脚本处理一下 [原始标注](http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/stuffthingmaps_trainval2017.zip) 就可以了。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MendelXu/SAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月18日(星期一) 晚上11:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MendelXu/SAN] 关于COCO-Stuff171数据集准备的问题 (Issue #50)





 
感谢您的提示，还想请教您在训练的过程中是否遇到过tgt_ids中的数字超出了out_prob的范围的情况,具体位置在BreadcrumbsSAN/san/model
 /matcher.py的116行cost_class = -out_prob[:, tgt_ids]，是因为我没有运行https://github.com/MendelXu/zsseg.baseline/blob/master/datasets/prepare_coco_stuff_164k_sem_seg.py的缘故吗

**Comment by GOZIHUATANEJO** [comment]
十分感谢您的回复，第一次使用coco数据集不是很了解，早上起来意识到自己问了个很蠢的问题后就删除了提问，再次感谢您的回复。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MendelXu/SAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月19日(星期二) 上午10:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MendelXu/SAN] 关于COCO-Stuff171数据集准备的问题 (Issue #50)





 反倒是您提醒了我，我因为之前什么时候已经处理得到了一个标签连续的标注目录，再次在上面做处理就出错了。 
 你的问题应该就是需要用那个脚本处理一下 [原始标注](http://calvin.inf.ed.ac.uk/wp-content/uploads/data/cocostuffdataset/stuffthingmaps_trainval2017.zip) 就可以了。 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "MendelXu/SAN"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年3月18日(星期一) 晚上11:08 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [MendelXu/SAN] 关于COCO-Stuff171数据集准备的问题 (Issue #50) 
 
 
 
 
 
   
 感谢您的提示，还想请教您在训练的过程中是否遇到过tgt_ids中的数字超出了out_prob的范围的情况,具体位置在BreadcrumbsSAN/san/model 
  /matcher.py的116行cost_class = -out_prob[:, tgt_ids]，是因为我没有运行https://github.com/MendelXu/zsseg.baseline/blob/master/datasets/prepare_coco_stuff_164k_sem_seg.py的缘故吗
