### ISSUE TITLE
Debug problem:AttributeError: Cannot find field 'gt_boxes' in the given Instances!

### ISSUE THREAD

**Issue by hiwmy0211** [MendelXu/SAN#57]
hello, thank you for your excellent work! I had a problem in running the train_net.py. The problem is AttributeError: Cannot find field 'gt_boxes' in the given Instances! I found that the gt_instances didn't have the gt_boxes, so how can i solve the problem?  thank you in advance for your reply.
![Uploading question.png…]()

**Comment by hiwmy0211** [comment]
![question](https://github.com/user-attachments/assets/e6516e16-568b-4c22-9b91-a1bd522f8718)

**Comment by hiwmy0211** [comment]
Sorry, I know where the problem is, and it has been solved, thank you!

**Comment by Kimsure** [comment]
The same issue occurs to me. How was it solved?

**Comment by 2fdsa3** [comment]
> The same issue occurs to me. How was it solved?

**Comment by jwfanDL** [comment]
The reason of this issue is using wrong configs
