### ISSUE TITLE
代码中的冻结参数设置

### ISSUE THREAD

**Issue by 007invictus** [MendelXu/SAN#7]
我好像只找到了冻结positional_embedding的代码。。其他的是怎么设置的呢

**Comment by MendelXu** [comment]
都是通过cfg.MODEL.SAN.CLIP_FROZEN_EXCLUDE实现的，你把不想冻结的部分的关键字放在这里面就可以了。

**Comment by MendelXu** [comment]
如果是想冻结positional_embedding部分，可以把MODEL.SAN.CLIP_FROZEN_EXCLUDE设置成 ["DUMMY"]
