### ISSUE TITLE
Training on multiple datasets

### ISSUE THREAD

**Issue by mojingtong** [MendelXu/SAN#8]
Thank you for your excellent work. I have some questions about training on multiple datasets. For example, I want to train the SAN model on both coco dataset and ade_20k dataset. There are errors when I change TRAIN in _Base-coco-stuff-164K-171.yaml_ due to the assertion _assert (len(list(set(dataset_names))) == 1), "All images in a batch must be from the same dataset."_ How to solve this problem? Thanks a lot!

**Comment by mojingtong** [comment]
Thanks a lot. I have clear understanding of this question, so I close the issue!

**Comment by buchannn** [comment]
> Thanks a lot. I have clear understanding of this question, so I close the issue!

Hi How did you finally solve the issue of training on multiple datasets? Looking forward to your response.
Thanks.
