### ISSUE TITLE
question about clip-aware and clip-unaware

### ISSUE THREAD

**Issue by jainie-max** [MendelXu/SAN#9]
Hi, great work! I have some questions about clip aware and clip unaware in the paper. Since the clip model is locked, why the gradients can pass through clip in an e2e training manner and block in a two-stage manner training in paper fig.5?

**Comment by MendelXu** [comment]
The fact that the model is locked  only means the parameters of the model will not be updated during training. The gradient of the activation still exists as the input to the deepr layer requires gradient.

**Comment by jainie-max** [comment]
get it！Tanks
